version: 1.0.{build}

branches:
  except:
  - gh-pages

skip_tags: true

image:
- Visual Studio 2017
- Ubuntu

install:
  - sh: chmod +x build.sh

build_script:
  - ps: .\build.ps1
  - sh: ./build.sh

test: off

test_script: off

after_test: off