name: build-test
on: [push]
jobs:
  build:
    name: solution
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0'
          include-prerelease: True
      - run: dotnet --version
      - name: Run Make CI
        run: make ci
      # - name: Build
      #   run: dotnet build
      # - name: Test
      #   run: dotnet test --collect:"XPlat Code Coverage"
      # - name: Install report-generator
      #   run: dotnet tool install -g dotnet-reportgenerator-globaltool
      # - name: Generate report
      #   run: reportgenerator "-reports:./src/tests/**/TestResults/**/coverage.cobertura.xml" "-targetdir:artifacts/coveragereport" "-reporttypes:Html"\
      # - name: Upload test coverage to codecov
      #   run: bash <(curl -s https://codecov.io/bash)
      #   if: matrix.os == 'ubuntu-latest'